---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.1-alpine
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_PASSWORD
            value: password123
          ports:
          - containerPort: 5432
            name: postgres
          volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/init.sql
            name: postgres-init
            subPath: init.sql
      volumes:
      - name: postgres-init
        configMap:
          name: postgres-init
